#!/bin/bash
if [ -z "$1" ]; then
    echo "usage: compiler file_name\ndo not add .asm" >&2
    exit 1
fi

# Check if the .asm file exists
if [ ! -f "$1.asm" ]; then
    echo "file '$1.asm' doesn't exist." >&2
    exit 1
fi
nasm -f bin -o $1 $1.asm
chmod +x $1
